# shellcheck shell=bash
# microbats — a bats-compatible test runner in pure bash 3.2.
#
# The pack promises a bash-only fallback, so its own suite must run with
# nothing installed. This understands the subset of bats-core syntax the suite
# uses — `@test` blocks, setup/teardown, load, run/$status/$output/$lines,
# skip — which keeps `test/run.sh` and a real `bats test/` interchangeable.
#
# Each test runs in its own bash process, so setup/teardown isolation and a
# leaked `cd` or `export` behave the same way they do under bats.

MICROBATS_LIB="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"

# Lines of generated preamble sitting above the first line of the .bats file.
# Used to map a failure back to a source line the reader can open.
MICROBATS_PREAMBLE_LINES=5

# ── child runtime: the API a test body sees ──────────────────────────────────

# Run a command without tripping `set -e`, capturing status/output/lines.
run() {
  local _restore_e=0
  case "$-" in *e*) _restore_e=1; set +e ;; esac

  output="$("$@" 2>&1)"
  status=$?

  lines=()
  local _line
  while IFS= read -r _line; do
    lines+=("$_line")
  done <<MICROBATS_EOF
$output
MICROBATS_EOF

  [ "$_restore_e" = 1 ] && set -e
  return 0
}

# Source a helper, bats-style: relative to the test file, `.bash` implied.
load() {
  local target="$1"
  case "$target" in
    /*) ;;
    *) target="$BATS_TEST_DIRNAME/$target" ;;
  esac
  [ -f "$target" ] || target="$target.bash"
  # shellcheck source=/dev/null
  . "$target"
}

skip() {
  MICROBATS_SKIPPED=1
  MICROBATS_SKIP_REASON="${1:-}"
  exit 0
}

microbats__is_fn() {
  declare -f "$1" >/dev/null 2>&1
}

# Report the failing line of the .bats file, not of whatever helper raised it.
# Walks the call stack down to the frame that lives in the generated file ($0)
# and translates it back through the fixed preamble offset.
microbats__on_err() {
  local rc="$1" i=1 line=""
  while [ "$i" -lt "${#BASH_SOURCE[@]}" ]; do
    if [ "${BASH_SOURCE[$i]}" = "$0" ]; then
      line="${BASH_LINENO[$((i - 1))]}"
      break
    fi
    i=$((i + 1))
  done
  if [ -n "$line" ]; then
    printf '%s:%s: failed (exit %s)\n' \
      "$BATS_TEST_FILENAME" "$((line - MICROBATS_PREAMBLE_LINES))" "$rc" >&2
  else
    printf '%s: failed (exit %s)\n' "$BATS_TEST_FILENAME" "$rc" >&2
  fi
}

microbats__on_exit() {
  local rc=$?
  set +eE
  trap - ERR
  if microbats__is_fn teardown; then teardown || true; fi
  if [ "${MICROBATS_SKIPPED:-0}" = 1 ]; then
    [ -n "${MICROBATS_SKIP_REASON:-}" ] && printf 'skipped: %s\n' "$MICROBATS_SKIP_REASON"
    exit 3
  fi
  exit "$rc"
}

# Entry point of a generated test file: run one test by index.
microbats__child() {
  local idx="${1:-}"
  if [ -z "$idx" ]; then
    echo "microbats: generated file needs a test index" >&2
    exit 99
  fi
  BATS_TEST_NUMBER="$idx"
  BATS_TEST_NAME="${2:-}"
  MICROBATS_SKIPPED=0
  MICROBATS_SKIP_REASON=""
  status=0
  output=""
  lines=()

  set -eE
  trap 'microbats__on_err "$?"' ERR
  trap 'microbats__on_exit' EXIT

  if microbats__is_fn setup; then setup; fi
  "microbats_test_$idx"
  exit 0
}

# ── parent runtime: compile and drive test files ─────────────────────────────

microbats__quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

# Turn `@test "name" {` into a function, one source line per generated line so
# reported line numbers stay meaningful. Test names go to a sidecar file.
microbats_compile() {
  local src="$1" out="$2" names="$3"
  {
    echo '#!/usr/bin/env bash'
    echo '# generated by microbats — do not edit'
    printf 'BATS_TEST_FILENAME=%s\n' "$(microbats__quote "$src")"
    printf 'BATS_TEST_DIRNAME=%s\n' "$(microbats__quote "$(cd "$(dirname "$src")" && pwd)")"
    printf '. %s\n' "$(microbats__quote "$MICROBATS_LIB")"
    awk -v namesfile="$names" '
      BEGIN { n = 0 }
      /^[ \t]*@test[ \t]/ {
        line = $0
        sub(/^[ \t]*@test[ \t]+/, "", line)
        sub(/[ \t]*\{[ \t]*$/, "", line)
        q = substr(line, 1, 1)
        if (q == "\"" || q == "\047") line = substr(line, 2, length(line) - 2)
        n++
        print line > namesfile
        print "microbats_test_" n "() {"
        next
      }
      { print }
    ' "$src"
    echo 'microbats__child "$@"'
  } >"$out"
}

microbats_run_file() {
  local src="$1"
  local work="$MICROBATS_WORKDIR/$(basename "$src")"
  local gen="$work/test.sh" names="$work/names.txt"
  mkdir -p "$work"
  : >"$names"
  microbats_compile "$src" "$gen" "$names"

  local count
  count=$(awk 'END { print NR }' "$names")

  printf '%s\n' "$src"
  local i=1 name rc out
  while [ "$i" -le "$count" ]; do
    name=$(sed -n "${i}p" "$names")
    if [ -n "${MICROBATS_FILTER:-}" ] && ! printf '%s' "$name" | grep -Eq "$MICROBATS_FILTER"; then
      i=$((i + 1))
      continue
    fi
    MICROBATS_TOTAL=$((MICROBATS_TOTAL + 1))
    out=$(bash "$gen" "$i" "$name" 2>&1) && rc=0 || rc=$?
    case "$rc" in
      0)
        printf '  ✓ %s\n' "$name"
        ;;
      3)
        MICROBATS_SKIPPED_COUNT=$((MICROBATS_SKIPPED_COUNT + 1))
        printf '  - %s (%s)\n' "$name" "${out:-skipped}"
        ;;
      *)
        MICROBATS_FAILED=$((MICROBATS_FAILED + 1))
        printf '  ✗ %s\n' "$name"
        printf '%s\n' "$out" | sed 's/^/      /'
        ;;
    esac
    i=$((i + 1))
  done
}

# Run every given .bats file; returns non-zero if any test failed.
microbats_main() {
  MICROBATS_TOTAL=0
  MICROBATS_FAILED=0
  MICROBATS_SKIPPED_COUNT=0
  MICROBATS_WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/microbats.XXXXXX")"
  trap 'rm -rf "$MICROBATS_WORKDIR"' EXIT

  local f
  for f in "$@"; do
    microbats_run_file "$f"
  done

  printf '\n%s tests, %s failures' "$MICROBATS_TOTAL" "$MICROBATS_FAILED"
  [ "$MICROBATS_SKIPPED_COUNT" -gt 0 ] && printf ', %s skipped' "$MICROBATS_SKIPPED_COUNT"
  printf '\n'

  [ "$MICROBATS_FAILED" -eq 0 ]
}
